<?xml version="1.0" encoding="utf-8"?><Database Name="RestauranteApp" Class="BaseDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHAVA;Initial Catalog=RestauranteApp;Integrated Security=True" SettingsObjectName="Restaurante_DAL.Properties.Settings" SettingsPropertyName="RestauranteAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Roles_Usuario" Member="Usuarios" ThisKey="Id" OtherKey="RolId" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.FacturaDetalle" Member="FacturaDetalle">
    <Type Name="FacturaDetalle">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoArticulo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="FacturaId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="FacturaEncabezado_FacturaDetalle" Member="FacturaEncabezado" ThisKey="FacturaId" OtherKey="Id" Type="FacturaEncabezado" IsForeignKey="true" />
      <Association Name="Articulo_FacturaDetalle" Member="Articulo" ThisKey="CodigoArticulo" OtherKey="Id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Equipo" Member="Equipos">
    <Type Name="Equipo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreEquipo" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Equipo_CajaDiaria" Member="CajaDiarias" ThisKey="Id" OtherKey="EquipoId" Type="CajaDiaria" />
    </Type>
  </Table>
  <Table Name="dbo.Movimiento" Member="Movimientos">
    <Type Name="Movimiento">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Movimiento_CajaDiaria" Member="CajaDiarias" ThisKey="Id" OtherKey="MovimientoId" Type="CajaDiaria" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Marcas_Personal" Member="Marcas_Personal" ThisKey="Id" OtherKey="Id_Usuario" Type="Marcas_Personal" />
      <Association Name="Usuario_FacturaEncabezado" Member="FacturaEncabezado" ThisKey="Id" OtherKey="UsuarioId" Type="FacturaEncabezado" />
      <Association Name="Roles_Usuario" Member="Roles" ThisKey="RolId" OtherKey="Id" Type="Roles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CajaDiaria" Member="CajaDiarias">
    <Type Name="CajaDiaria">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovimientoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ComprobanteId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EquipoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AutorizadoPor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacturaId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Equipo_CajaDiaria" Member="Equipo" ThisKey="EquipoId" OtherKey="Id" Type="Equipo" IsForeignKey="true" />
      <Association Name="Movimiento_CajaDiaria" Member="Movimiento" ThisKey="MovimientoId" OtherKey="Id" Type="Movimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObtieneGastos_Vw" Member="ObtieneGastos_Vws">
    <Type Name="ObtieneGastos_Vw">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ComprobanteId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="EquipoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VentasArticulo_Vw" Member="VentasArticulo_Vws">
    <Type Name="VentasArticulo_Vw">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Familia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IVA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PrecioIVA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CantidadVendida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Familias" Member="Familias">
    <Type Name="Familia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Guarnicion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EsGuarnicion" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Familia_Articulo" Member="Articulo" ThisKey="Id" OtherKey="FamiliaId" Type="Articulo" />
    </Type>
  </Table>
  <Table Name="dbo.ObtieneArticulos" Member="ObtieneArticulos">
    <Type Name="ObtieneArticulo">
      <Column Name="Id" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="FamiliaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Costo" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ObtieneConsumoMesaHora" Member="ObtieneConsumoMesaHoras">
    <Type Name="ObtieneConsumoMesaHora">
      <Column Name="Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Mesa_Silla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoArticulo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="Eliminar" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ObtieneConsumoMesa" Member="ObtieneConsumoMesas">
    <Type Name="ObtieneConsumoMesa">
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Mesa_Silla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CodigoArticulo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(29,2)" CanBeNull="true" />
      <Column Name="Eliminar" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ImpresionComandaCocina" Member="ImpresionComandaCocinas">
    <Type Name="ImpresionComandaCocina">
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Mesa_Silla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Eliminar" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Marcas_Personal" Member="Marcas_Personal">
    <Type Name="Marcas_Personal">
      <Column Name="Id_Usuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Hora_Entrada" AutoSync="Never" Type="System.TimeSpan" DbType="Time NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hora_Salida" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="Usuario_Marcas_Personal" Member="Usuario" ThisKey="Id_Usuario" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObtieneVentas_Vw" Member="ObtieneVentas_Vw">
    <Type Name="ObtieneVentas_Vw">
      <Column Name="TipoPago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(23)" CanBeNull="true" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ClienteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MovimientoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ImpresionComandaBar" Member="ImpresionComandaBar">
    <Type Name="ImpresionComandaBar">
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Mesa_Silla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Eliminar" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FacturaEncabezado" Member="FacturaEncabezado">
    <Type Name="FacturaEncabezado">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Descuento" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Recibido" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Propina" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ClienteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MesaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoPago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FacturaEncabezado_FacturaDetalle" Member="FacturaDetalle" ThisKey="Id" OtherKey="FacturaId" Type="FacturaDetalle" />
      <Association Name="Usuario_FacturaEncabezado" Member="Usuario" ThisKey="UsuarioId" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Articulo" Member="Articulo">
    <Type Name="Articulo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FamiliaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Costo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Existencias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Inventariado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Comanda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Articulo_FacturaDetalle" Member="FacturaDetalle" ThisKey="Id" OtherKey="CodigoArticulo" Type="FacturaDetalle" />
      <Association Name="Articulo_TemporalConsumo" Member="TemporalConsumo" ThisKey="Id" OtherKey="CodigoArticulo" Type="TemporalConsumo" />
      <Association Name="Familia_Articulo" Member="Familia" ThisKey="FamiliaId" OtherKey="Id" Type="Familia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TemporalConsumo" Member="TemporalConsumo">
    <Type Name="TemporalConsumo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodigoArticulo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mesa_Silla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Detalle" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="Hora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Articulo_TemporalConsumo" Member="Articulo" ThisKey="CodigoArticulo" OtherKey="Id" Type="Articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.barrio" Member="barrio">
    <Type Name="barrio">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigoProvincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigoCanton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigoDistrito" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="barrio" Member="barrio1" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.canton" Member="canton">
    <Type Name="canton">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigoProvincia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="canton" Member="canton1" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.distrito" Member="distrito">
    <Type Name="distrito">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigoProvincia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigoCanton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="distrito" Member="distrito1" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Facturas_Electronicas" Member="Facturas_Electronicas">
    <Type Name="Facturas_Electronicas">
      <Column Name="id_FacturaElectronica" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Numero_Factura_Local" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XML_Factura" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Monto_Factura" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Cancelada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enviada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Persona" Member="Persona">
    <Type Name="Persona">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ident_Tipo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ident_Numero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NombreComercial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ubi_Provicia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ubi_Canton" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ubi_Distrito" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ubi_OtrasSenas" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tel_CodigoPais" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tel_NumeroTelefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax_CodigoPais" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax_NumeroTelefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Emisor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Receptor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_persona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.provincia" Member="provincia">
    <Type Name="provincia">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="provincia" Member="provincia1" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tiquetes_Electronicos" Member="Tiquetes_Electronicos">
    <Type Name="Tiquetes_Electronicos">
      <Column Name="id_TiqueteElectronico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Numero_Factura_Local" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XML_Factura" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Monto_Factura" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Cancelada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Enviada" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InformacionGeneral" Member="InformacionGeneral">
    <Type Name="InformacionGeneral">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Dueno" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PiePagina1" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PiePagina2" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PiePagina3" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PiePagina4" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FinalPagina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Web" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Impresora" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IVA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ImpuestoServicio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TipoCambio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Numero_Sucursal" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Numero_Cedula" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.get_Consect_Factura" Method="get_Consect_Factura">
    <Parameter Name="total" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_Consect_Tiquete" Method="get_Consect_Tiquete">
    <Parameter Name="total" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>