//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVentaDAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-N186HAJ;Initial Catalog=PuntoVentaAutoPartsOnDemand;Persist S" +
            "ecurity Info=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:DIGITALMATTER,1433;Initial Catalog=PuntoVentaAutoPartsOnDemand;Us" +
            "er ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString1 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TCP:10.210.52.131,1433;Initial Catalog=PuntoVenta;Persist Security In" +
            "fo=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString2 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=josepablo-pc;Initial Catalog=PuntoVentaAutoPartsOnDemand;Integrated S" +
            "ecurity=True")]
        public string PuntoVentaAutoPartsOnDemandConnectionString3 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-3QGU8GE;Initial Catalog=supercincoesquinas;Integrated Securit" +
            "y=True")]
        public string PuntoVentaAutoPartsOnDemandConnectionString4 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=PuntoVenta;Persist Security Info=True;Use" +
            "r ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString5 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.122;Initial Catalog=PuntoVenta;Persist Security Info=True;U" +
            "ser ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString6 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YILENYPC;Initial Catalog=PuntoVentaAutoPartsOnDemand;Persist Security" +
            " Info=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString7 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.116;Initial Catalog=PuntoVentaAutoPartsOnDemand;Persist Sec" +
            "urity Info=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString8 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.103;Initial Catalog=PuntoVentaAutoPartsOnDemand;Persist Sec" +
            "urity Info=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString9 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EQUIPO-RICARDO\\SQLEXPRESS;Initial Catalog=PuntoVentaAutoPartsOnDemand" +
            ";Persist Security Info=True;User ID=sa;Password=123")]
        public string PuntoVentaAutoPartsOnDemandConnectionString10 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.100;Initial Catalog=PuntoVentaAutoPartsOnDemand;Persist Se" +
            "curity Info=True;User ID=sa;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString11 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROBERTGONZALEZ;Initial Catalog=PuntoVentaAutoPartsOnDemand;Integrated" +
            " Security=True")]
        public string PuntoVentaAutoPartsOnDemandConnectionString12 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-N186HAJ;Initial Catalog=PuntoVentaAutoPartsOnDemand;User ID=s" +
            "a;Password=sa2015")]
        public string PuntoVentaAutoPartsOnDemandConnectionString13 {
            get {
                return ((string)(this["PuntoVentaAutoPartsOnDemandConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROJAS;Initial Catalog=CincoEsquinas2;User ID=sa;Password=sa2015")]
        public string CincoEsquinas2ConnectionString14 {
            get {
                return ((string)(this["CincoEsquinas2ConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EQUIPO-RICARDO\\SQLEXPRESSR2;Initial Catalog=PuntoVentaAutoPartsOnDema" +
            "nd;User ID=sa;Password=123")]
        public string CincoEsquinas2ConnectionString {
            get {
                return ((string)(this["CincoEsquinas2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=rojas;Initial Catalog=CincoEsquinas2;User ID=sa;Password=sa2015")]
        public string CincoEsquinas2ConnectionString2 {
            get {
                return ((string)(this["CincoEsquinas2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROJAS;Initial Catalog=supercincoesquinas2;User ID=sa;Password=sa2015")]
        public string SuperConnectionString {
            get {
                return ((string)(this["SuperConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LV4FM6N;Initial Catalog=PuntoVentaAutoPartsOnDemand;User ID=s" +
            "a;Password=sa2015")]
        public string SuperConnectionString2 {
            get {
                return ((string)(this["SuperConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EQUIPO-RICARDO\\SQLEXPRESSR2;Initial Catalog=PuntoVentaCristal;User ID" +
            "=sa;Password=123")]
        public string SuperConnectionString3 {
            get {
                return ((string)(this["SuperConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.210.52.131;Initial Catalog=PuntoVenta;User ID=sa;Password=sa2015")]
        public string SuperConnectionString4 {
            get {
                return ((string)(this["SuperConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.116;Initial Catalog=PuntoVentaAutoPartsOnDemand;User ID=sa;" +
            "Password=sa2015")]
        public string SuperConnectionString5 {
            get {
                return ((string)(this["SuperConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LPI02LJ\\SQLEXPRESS;Initial Catalog=FacturaElectronica;User ID" +
            "=sa;Password=sa2015")]
        public string FacturaElectronicaConectionString {
            get {
                return ((string)(this["FacturaElectronicaConectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LPI02LJ\\SQLEXPRESS;Initial Catalog=FacturaElectronica;Persist" +
            " Security Info=True;User ID=sa;Password=sa2015")]
        public string FacturaElectronicaConnectionString {
            get {
                return ((string)(this["FacturaElectronicaConnectionString"]));
            }
        }
    }
}
